spring.application.name=hardware-backend

# MYSQL CONFIGURATION
spring.datasource.url=jdbc:mysql://localhost:3306/database
spring.datasource.username=root
spring.datasource.password=

# JPA CONFIGURATION
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

#Spring
spring.security.oauth2.client.registration.google.client-id=942783526563-obj728rahrp8ocoqs7orasqamqjut4iu.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email



